; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitc-1]

platform  = espressif32
board     = esp32-s3-devkitc-1
framework = arduino

; ── Flash + PSRAM (ESP32-S3R8 = QIO Flash, OPI PSRAM 8MB) ──
board_build.flash_mode           = qio
board_build.psram_type           = opi
board_build.arduino.memory_type  = qio_opi   ; ← LIGNE CRITIQUE

; ── Mémoire ─────────────────────────────────────────────────
board_upload.flash_size          = 16MB
board_upload.maximum_size        = 16777216
board_build.partitions           = default_16MB.csv

; ── Build flags ──────────────────────────────────────────────
build_flags =
    -DBOARD_HAS_PSRAM

; ── Serial ───────────────────────────────────────────────────
upload_speed                     = 921600
monitor_speed                    = 115200

; ── Bibliothèques ────────────────────────────────────────────
lib_deps =
    plerup/EspSoftwareSerial
    mikalhart/TinyGPSPlus
    knolleary/PubSubClient
    bblanchon/ArduinoJson